# Generated by Django 2.0 on 2018-01-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('UT', 'Utilisateur'), ('TH', 'Therapeute')], default='UT', max_length=2)),
                ('nom', models.CharField(help_text='Nom', max_length=30)),
                ('prenom1', models.CharField(help_text='Prénom', max_length=30)),
                ('prenom2', models.CharField(help_text='Deuxième Prénom', max_length=30)),
                ('date_de_naissance', models.CharField(help_text='Date de Naissance', max_length=8)),
                ('pays', models.CharField(help_text='Pays de Résidence', max_length=30)),
                ('ville', models.CharField(help_text='Ville', max_length=30)),
                ('langue', models.CharField(help_text='Nom', max_length=30)),
                ('adresse_mail', models.EmailField(help_text='Nom', max_length=254)),
            ],
        ),
    ]
