# Generated by Django 2.1.dev20180125184051 on 2018-02-01 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colonne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation', models.TextField(help_text='Décrivez la Situation', max_length=30)),
                ('pensee_aut', models.TextField(help_text='Pensée automatique', max_length=30)),
                ('pensee_alt', models.TextField(help_text='Pensée alternative', max_length=30)),
                ('date_ajout', models.DateTimeField(auto_now=True, help_text="Date de l'ajout")),
                ('date_event', models.DateTimeField(help_text="Date de l'événement")),
            ],
        ),
        migrations.CreateModel(
            name='Conseil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conseil', models.CharField(help_text='Type du conseil', max_length=30)),
                ('contenu_conseil', models.CharField(help_text='Contenu du conseil', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_emo', models.CharField(help_text="Non de l'émotion", max_length=30)),
                ('intensite', models.IntegerField(help_text="Intensité de l'émotion")),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('UT', 'Utilisateur'), ('TH', 'Therapeute')], default='UT', max_length=2)),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(default='', max_length=30)),
                ('date_de_naissance', models.CharField(max_length=8)),
                ('pays', models.CharField(max_length=30)),
                ('ville', models.CharField(max_length=30)),
                ('langue', models.CharField(max_length=30)),
                ('adresse_mail', models.EmailField(max_length=254)),
                ('mot_de_passe', models.CharField(default='', max_length=30)),
                ('lien_therapeute', models.ManyToManyField(related_name='_personne_lien_therapeute_+', to='colonnes.Personne')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_tag', models.CharField(help_text='Entrez un Tag', max_length=30)),
                ('type_tag', models.CharField(help_text='Famille du tag', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='colonne',
            name='emo_alt',
            field=models.ManyToManyField(related_name='colonne_alternative', to='colonnes.Emotion'),
        ),
        migrations.AddField(
            model_name='colonne',
            name='emo_aut',
            field=models.ManyToManyField(related_name='colonne_automatique', to='colonnes.Emotion'),
        ),
        migrations.AddField(
            model_name='colonne',
            name='personne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colonnes.Personne'),
        ),
        migrations.AddField(
            model_name='colonne',
            name='tag',
            field=models.ManyToManyField(to='colonnes.Tag'),
        ),
    ]
