# Generated by Django 2.0 on 2018-01-31 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colonnes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personne',
            name='prenom2',
        ),
    ]
