# Generated by Django 2.1.dev20180125184051 on 2018-02-01 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colonnes', '0002_auto_20180201_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='lien_therapeute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='colonnes.Personne'),
        ),
    ]
