# Generated by Django 2.0 on 2018-01-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colonnes', '0002_remove_personne_prenom2'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='mot_de_passe',
            field=models.CharField(default='', help_text="Mot de passe permettant de sécuriser votre compte, et l'accès à vos données.", max_length=30),
        ),
    ]
