# Generated by Django 2.0 on 2018-01-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colonnes', '0003_personne_mot_de_passe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personne',
            name='prenom1',
        ),
        migrations.AddField(
            model_name='personne',
            name='prenom',
            field=models.CharField(default='', help_text='Prénom', max_length=30),
        ),
    ]
