# Generated by Django 2.1.dev20180125184051 on 2018-02-02 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colonnes', '0004_auto_20180201_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colonne',
            name='personne',
        ),
        migrations.AddField(
            model_name='colonne',
            name='utilisateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colonne',
            name='pensee_alt',
            field=models.TextField(help_text='Pensée alternative', max_length=500),
        ),
        migrations.AlterField(
            model_name='colonne',
            name='pensee_aut',
            field=models.TextField(help_text='Pensée automatique', max_length=500),
        ),
        migrations.AlterField(
            model_name='colonne',
            name='situation',
            field=models.TextField(help_text='Décrivez la Situation', max_length=1000),
        ),
        migrations.AlterField(
            model_name='conseil',
            name='contenu_conseil',
            field=models.CharField(help_text='Contenu du conseil', max_length=400),
        ),
        migrations.AlterField(
            model_name='personne',
            name='date_de_naissance',
            field=models.DateField(),
        ),
    ]
