# Generated by Django 2.1.dev20180125184051 on 2018-02-02 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colonnes', '0005_auto_20180202_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lien_Ut_Th',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lien_ut_th_therapeute', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lien_ut_th_utilisateur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
