# Generated by Django 2.1.dev20180125184051 on 2018-02-01 18:32

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colonnes', '0005_auto_20180131_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colonne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation', models.TextField(help_text='Décrivez la Situation', max_length=30)),
                ('pensee_aut', models.TextField(help_text='Pensée automatique', max_length=30)),
                ('pensee_alt', models.TextField(help_text='Pensée alternative', max_length=30)),
                ('date_ajout', models.DateTimeField(auto_now=True, help_text="Date de l'ajout")),
                ('date_event', models.DateTimeField(help_text="Date de l'événement")),
            ],
        ),
        migrations.CreateModel(
            name='Conseil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conseil', models.CharField(help_text='Type du conseil', max_length=30)),
                ('contenu_conseil', models.CharField(help_text='Contenu du conseil', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_emo', models.CharField(help_text="Non de l'émotion", max_length=30)),
                ('intensite', models.IntegerField(help_text="Intensité de l'émotion")),
            ],
        ),
        migrations.CreateModel(
            name='Lien_Emotion_Colonne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_emotion', models.CharField(choices=[('AL', 'Alternative'), ('RE', 'Ressentie')], default='RE', max_length=2)),
                ('colonne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colonnes.Colonne')),
                ('emotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colonnes.Emotion')),
            ],
        ),
        migrations.CreateModel(
            name='Lien_Tag_Colonne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colonnes.Colonne')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_tag', models.CharField(help_text='Entrez un Tag', max_length=30)),
                ('type_tag', models.CharField(help_text='Famille du tag', max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='personne',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='personne',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='personne',
            name='id',
        ),
        migrations.AddField(
            model_name='personne',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lien_tag_colonne',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colonnes.Tag'),
        ),
        migrations.AddField(
            model_name='emotion',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colonnes.Tag'),
        ),
        migrations.AddField(
            model_name='colonne',
            name='personne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colonnes.Personne'),
        ),
    ]
