# Generated by Django 2.0 on 2018-02-03 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colonnes', '0006_lien_ut_th'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emotion',
            name='intensite',
        ),
    ]
