# Generated by Django 2.1.dev20180125184051 on 2018-02-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colonnes', '0006_auto_20180201_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personne',
            options={},
        ),
        migrations.AlterModelManagers(
            name='personne',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='personne',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='personne',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
