# Generated by Django 2.1.dev20180125184051 on 2018-02-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colonnes', '0007_auto_20180201_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='colonne',
            name='emo_alt',
            field=models.ManyToManyField(related_name='colonne_alternative', to='colonnes.Emotion'),
        ),
        migrations.AddField(
            model_name='colonne',
            name='emo_aut',
            field=models.ManyToManyField(related_name='colonne_automatique', to='colonnes.Emotion'),
        ),
        migrations.AddField(
            model_name='colonne',
            name='tag',
            field=models.ManyToManyField(to='colonnes.Tag'),
        ),
        migrations.AddField(
            model_name='personne',
            name='lien_therapeute',
            field=models.ManyToManyField(related_name='_personne_lien_therapeute_+', to='colonnes.Personne'),
        ),
    ]
