# Generated by Django 2.1.dev20180125184051 on 2018-02-01 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colonnes', '0008_auto_20180201_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lien_emotion_colonne',
            name='colonne',
        ),
        migrations.RemoveField(
            model_name='lien_emotion_colonne',
            name='emotion',
        ),
        migrations.RemoveField(
            model_name='lien_tag_colonne',
            name='col',
        ),
        migrations.RemoveField(
            model_name='lien_tag_colonne',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Lien_Emotion_Colonne',
        ),
        migrations.DeleteModel(
            name='Lien_Tag_Colonne',
        ),
    ]
