# Generated by Django 2.0 on 2018-02-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colonnes', '0009_remove_tag_type_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='colonne',
            name='emotion',
            field=models.CharField(choices=[('JO', 'Joie'), ('CO', 'Colère'), ('TR', 'Tristesse'), ('DE', 'Dégoût'), ('PE', 'Peur')], default='JO', max_length=2),
        ),
    ]
