# Generated by Django 2.1.dev20180125184051 on 2018-02-01 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colonnes', '0009_auto_20180201_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emotion',
            name='tag',
        ),
    ]
