# Generated by Django 2.0 on 2018-02-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colonnes', '0011_colonne_intensite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colonne',
            name='intensite',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1),
        ),
    ]
