# Generated by Django 2.0 on 2018-02-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colonnes', '0020_auto_20180203_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='nom_tag',
            field=models.TextField(help_text='Entrez un Tag', max_length=30),
        ),
    ]
