# Generated by Django 2.0 on 2018-02-04 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colonnes', '0023_tag_utilisateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistiques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDeDebut', models.DateTimeField()),
                ('dateDeFin', models.DateTimeField()),
                ('emotion', models.CharField(choices=[('TO', 'Toutes'), ('JO', 'Joie'), ('CO', 'Colère'), ('TR', 'Tristesse'), ('DE', 'Dégoût'), ('PE', 'Peur')], default='TO', max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='personne',
            name='lien_therapeute',
        ),
        migrations.AddField(
            model_name='emotion',
            name='utilisateur',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Personne',
        ),
    ]
