# Generated by Django 2.1.dev20180125184051 on 2018-02-04 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colonnes', '0024_auto_20180204_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lien_ut_th',
            old_name='user',
            new_name='pati',
        ),
    ]
