# Generated by Django 2.0.1 on 2018-02-03 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colonnes', '0024_emotion_utilisateur'),
        ('colonnes', '0007_auto_20180203_1748'),
    ]

    operations = [
    ]
