# Generated by Django 2.0 on 2018-02-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colonnes', '0025_auto_20180204_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='statut_emo',
            field=models.CharField(help_text="Nom de l'émotion", max_length=30),
        ),
    ]
